---
# Setting up mysql

- name: Start the MySQL service
  service: name=mysql.service state=started enabled=yes


- name: Update MySQL root password
  mysql_user: 
    name: root 
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 


# TODO: Hashing passwords would be a plus!
- name: Creating regular user into MySQL.
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_app_user }}"
    password: "{{ mysql_app_password }}"
    encrypted: no
    priv: '*.*:ALL'
    state: present


- name: Creating the database for Flask
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_app_database }}"
    encoding: "{{ mysql_app_charset }}"
    collation: "{{ mysql_app_collation }}"
    state: present
