---
# Handler to handle restart notifications

- name: Systemd restart flask
  listen: "restart flask"
  systemd:
    name: flask_polls
    state: restarted
    daemon_reload: yes
    enabled: yes


- name: Systemd reload nginx
  listen: "reload nginx"
  systemd:
    name: nginx.service
    state: reloaded
    daemon_reload: yes
    enabled: yes
